// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/umputun/tg-spam/lib/approved"
	"sync"
)

// ApprovedUsersStoreMock is a mock implementation of webapi.ApprovedUsersStore.
//
//	func TestSomethingThatUsesApprovedUsersStore(t *testing.T) {
//
//		// make and configure a mocked webapi.ApprovedUsersStore
//		mockedApprovedUsersStore := &ApprovedUsersStoreMock{
//			DeleteByGIDFunc: func(ctx context.Context, gid string, id string) error {
//				panic("mock out the DeleteByGID method")
//			},
//			ReadByGIDFunc: func(ctx context.Context, gid string) ([]approved.UserInfo, error) {
//				panic("mock out the ReadByGID method")
//			},
//			WriteByGIDFunc: func(ctx context.Context, gid string, user approved.UserInfo) error {
//				panic("mock out the WriteByGID method")
//			},
//		}
//
//		// use mockedApprovedUsersStore in code that requires webapi.ApprovedUsersStore
//		// and then make assertions.
//
//	}
type ApprovedUsersStoreMock struct {
	// DeleteByGIDFunc mocks the DeleteByGID method.
	DeleteByGIDFunc func(ctx context.Context, gid string, id string) error

	// ReadByGIDFunc mocks the ReadByGID method.
	ReadByGIDFunc func(ctx context.Context, gid string) ([]approved.UserInfo, error)

	// WriteByGIDFunc mocks the WriteByGID method.
	WriteByGIDFunc func(ctx context.Context, gid string, user approved.UserInfo) error

	// calls tracks calls to the methods.
	calls struct {
		// DeleteByGID holds details about calls to the DeleteByGID method.
		DeleteByGID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gid is the gid argument value.
			Gid string
			// ID is the id argument value.
			ID string
		}
		// ReadByGID holds details about calls to the ReadByGID method.
		ReadByGID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gid is the gid argument value.
			Gid string
		}
		// WriteByGID holds details about calls to the WriteByGID method.
		WriteByGID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gid is the gid argument value.
			Gid string
			// User is the user argument value.
			User approved.UserInfo
		}
	}
	lockDeleteByGID sync.RWMutex
	lockReadByGID   sync.RWMutex
	lockWriteByGID  sync.RWMutex
}

// DeleteByGID calls DeleteByGIDFunc.
func (mock *ApprovedUsersStoreMock) DeleteByGID(ctx context.Context, gid string, id string) error {
	if mock.DeleteByGIDFunc == nil {
		panic("ApprovedUsersStoreMock.DeleteByGIDFunc: method is nil but ApprovedUsersStore.DeleteByGID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Gid string
		ID  string
	}{
		Ctx: ctx,
		Gid: gid,
		ID:  id,
	}
	mock.lockDeleteByGID.Lock()
	mock.calls.DeleteByGID = append(mock.calls.DeleteByGID, callInfo)
	mock.lockDeleteByGID.Unlock()
	return mock.DeleteByGIDFunc(ctx, gid, id)
}

// DeleteByGIDCalls gets all the calls that were made to DeleteByGID.
// Check the length with:
//
//	len(mockedApprovedUsersStore.DeleteByGIDCalls())
func (mock *ApprovedUsersStoreMock) DeleteByGIDCalls() []struct {
	Ctx context.Context
	Gid string
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		Gid string
		ID  string
	}
	mock.lockDeleteByGID.RLock()
	calls = mock.calls.DeleteByGID
	mock.lockDeleteByGID.RUnlock()
	return calls
}

// ResetDeleteByGIDCalls reset all the calls that were made to DeleteByGID.
func (mock *ApprovedUsersStoreMock) ResetDeleteByGIDCalls() {
	mock.lockDeleteByGID.Lock()
	mock.calls.DeleteByGID = nil
	mock.lockDeleteByGID.Unlock()
}

// ReadByGID calls ReadByGIDFunc.
func (mock *ApprovedUsersStoreMock) ReadByGID(ctx context.Context, gid string) ([]approved.UserInfo, error) {
	if mock.ReadByGIDFunc == nil {
		panic("ApprovedUsersStoreMock.ReadByGIDFunc: method is nil but ApprovedUsersStore.ReadByGID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Gid string
	}{
		Ctx: ctx,
		Gid: gid,
	}
	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = append(mock.calls.ReadByGID, callInfo)
	mock.lockReadByGID.Unlock()
	return mock.ReadByGIDFunc(ctx, gid)
}

// ReadByGIDCalls gets all the calls that were made to ReadByGID.
// Check the length with:
//
//	len(mockedApprovedUsersStore.ReadByGIDCalls())
func (mock *ApprovedUsersStoreMock) ReadByGIDCalls() []struct {
	Ctx context.Context
	Gid string
} {
	var calls []struct {
		Ctx context.Context
		Gid string
	}
	mock.lockReadByGID.RLock()
	calls = mock.calls.ReadByGID
	mock.lockReadByGID.RUnlock()
	return calls
}

// ResetReadByGIDCalls reset all the calls that were made to ReadByGID.
func (mock *ApprovedUsersStoreMock) ResetReadByGIDCalls() {
	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = nil
	mock.lockReadByGID.Unlock()
}

// WriteByGID calls WriteByGIDFunc.
func (mock *ApprovedUsersStoreMock) WriteByGID(ctx context.Context, gid string, user approved.UserInfo) error {
	if mock.WriteByGIDFunc == nil {
		panic("ApprovedUsersStoreMock.WriteByGIDFunc: method is nil but ApprovedUsersStore.WriteByGID was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Gid  string
		User approved.UserInfo
	}{
		Ctx:  ctx,
		Gid:  gid,
		User: user,
	}
	mock.lockWriteByGID.Lock()
	mock.calls.WriteByGID = append(mock.calls.WriteByGID, callInfo)
	mock.lockWriteByGID.Unlock()
	return mock.WriteByGIDFunc(ctx, gid, user)
}

// WriteByGIDCalls gets all the calls that were made to WriteByGID.
// Check the length with:
//
//	len(mockedApprovedUsersStore.WriteByGIDCalls())
func (mock *ApprovedUsersStoreMock) WriteByGIDCalls() []struct {
	Ctx  context.Context
	Gid  string
	User approved.UserInfo
} {
	var calls []struct {
		Ctx  context.Context
		Gid  string
		User approved.UserInfo
	}
	mock.lockWriteByGID.RLock()
	calls = mock.calls.WriteByGID
	mock.lockWriteByGID.RUnlock()
	return calls
}

// ResetWriteByGIDCalls reset all the calls that were made to WriteByGID.
func (mock *ApprovedUsersStoreMock) ResetWriteByGIDCalls() {
	mock.lockWriteByGID.Lock()
	mock.calls.WriteByGID = nil
	mock.lockWriteByGID.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *ApprovedUsersStoreMock) ResetCalls() {
	mock.lockDeleteByGID.Lock()
	mock.calls.DeleteByGID = nil
	mock.lockDeleteByGID.Unlock()

	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = nil
	mock.lockReadByGID.Unlock()

	mock.lockWriteByGID.Lock()
	mock.calls.WriteByGID = nil
	mock.lockWriteByGID.Unlock()
}
