// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/umputun/tg-spam/app/storage"
	"sync"
	"time"
)

// DetectedSpamMock is a mock implementation of webapi.DetectedSpam.
//
//	func TestSomethingThatUsesDetectedSpam(t *testing.T) {
//
//		// make and configure a mocked webapi.DetectedSpam
//		mockedDetectedSpam := &DetectedSpamMock{
//			FindByUserIDFunc: func(ctx context.Context, userID int64) (*storage.DetectedSpamInfo, error) {
//				panic("mock out the FindByUserID method")
//			},
//			ReadFunc: func(ctx context.Context) ([]storage.DetectedSpamInfo, error) {
//				panic("mock out the Read method")
//			},
//			ReadByGIDFunc: func(ctx context.Context, gid string) ([]storage.DetectedSpamInfo, error) {
//				panic("mock out the ReadByGID method")
//			},
//			ReadByGIDAndDateRangeFunc: func(ctx context.Context, gid string, from time.Time, to time.Time) ([]storage.DetectedSpamInfo, error) {
//				panic("mock out the ReadByGIDAndDateRange method")
//			},
//			SetAddedToSamplesFlagFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the SetAddedToSamplesFlag method")
//			},
//		}
//
//		// use mockedDetectedSpam in code that requires webapi.DetectedSpam
//		// and then make assertions.
//
//	}
type DetectedSpamMock struct {
	// FindByUserIDFunc mocks the FindByUserID method.
	FindByUserIDFunc func(ctx context.Context, userID int64) (*storage.DetectedSpamInfo, error)

	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context) ([]storage.DetectedSpamInfo, error)

	// ReadByGIDFunc mocks the ReadByGID method.
	ReadByGIDFunc func(ctx context.Context, gid string) ([]storage.DetectedSpamInfo, error)

	// ReadByGIDAndDateRangeFunc mocks the ReadByGIDAndDateRange method.
	ReadByGIDAndDateRangeFunc func(ctx context.Context, gid string, from time.Time, to time.Time) ([]storage.DetectedSpamInfo, error)

	// SetAddedToSamplesFlagFunc mocks the SetAddedToSamplesFlag method.
	SetAddedToSamplesFlagFunc func(ctx context.Context, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// FindByUserID holds details about calls to the FindByUserID method.
		FindByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ReadByGID holds details about calls to the ReadByGID method.
		ReadByGID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gid is the gid argument value.
			Gid string
		}
		// ReadByGIDAndDateRange holds details about calls to the ReadByGIDAndDateRange method.
		ReadByGIDAndDateRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Gid is the gid argument value.
			Gid string
			// From is the from argument value.
			From time.Time
			// To is the to argument value.
			To time.Time
		}
		// SetAddedToSamplesFlag holds details about calls to the SetAddedToSamplesFlag method.
		SetAddedToSamplesFlag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
	}
	lockFindByUserID          sync.RWMutex
	lockRead                  sync.RWMutex
	lockReadByGID             sync.RWMutex
	lockReadByGIDAndDateRange sync.RWMutex
	lockSetAddedToSamplesFlag sync.RWMutex
}

// FindByUserID calls FindByUserIDFunc.
func (mock *DetectedSpamMock) FindByUserID(ctx context.Context, userID int64) (*storage.DetectedSpamInfo, error) {
	if mock.FindByUserIDFunc == nil {
		panic("DetectedSpamMock.FindByUserIDFunc: method is nil but DetectedSpam.FindByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = append(mock.calls.FindByUserID, callInfo)
	mock.lockFindByUserID.Unlock()
	return mock.FindByUserIDFunc(ctx, userID)
}

// FindByUserIDCalls gets all the calls that were made to FindByUserID.
// Check the length with:
//
//	len(mockedDetectedSpam.FindByUserIDCalls())
func (mock *DetectedSpamMock) FindByUserIDCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockFindByUserID.RLock()
	calls = mock.calls.FindByUserID
	mock.lockFindByUserID.RUnlock()
	return calls
}

// ResetFindByUserIDCalls reset all the calls that were made to FindByUserID.
func (mock *DetectedSpamMock) ResetFindByUserIDCalls() {
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = nil
	mock.lockFindByUserID.Unlock()
}

// Read calls ReadFunc.
func (mock *DetectedSpamMock) Read(ctx context.Context) ([]storage.DetectedSpamInfo, error) {
	if mock.ReadFunc == nil {
		panic("DetectedSpamMock.ReadFunc: method is nil but DetectedSpam.Read was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedDetectedSpam.ReadCalls())
func (mock *DetectedSpamMock) ReadCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ResetReadCalls reset all the calls that were made to Read.
func (mock *DetectedSpamMock) ResetReadCalls() {
	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()
}

// ReadByGID calls ReadByGIDFunc.
func (mock *DetectedSpamMock) ReadByGID(ctx context.Context, gid string) ([]storage.DetectedSpamInfo, error) {
	if mock.ReadByGIDFunc == nil {
		panic("DetectedSpamMock.ReadByGIDFunc: method is nil but DetectedSpam.ReadByGID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Gid string
	}{
		Ctx: ctx,
		Gid: gid,
	}
	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = append(mock.calls.ReadByGID, callInfo)
	mock.lockReadByGID.Unlock()
	return mock.ReadByGIDFunc(ctx, gid)
}

// ReadByGIDCalls gets all the calls that were made to ReadByGID.
// Check the length with:
//
//	len(mockedDetectedSpam.ReadByGIDCalls())
func (mock *DetectedSpamMock) ReadByGIDCalls() []struct {
	Ctx context.Context
	Gid string
} {
	var calls []struct {
		Ctx context.Context
		Gid string
	}
	mock.lockReadByGID.RLock()
	calls = mock.calls.ReadByGID
	mock.lockReadByGID.RUnlock()
	return calls
}

// ResetReadByGIDCalls reset all the calls that were made to ReadByGID.
func (mock *DetectedSpamMock) ResetReadByGIDCalls() {
	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = nil
	mock.lockReadByGID.Unlock()
}

// ReadByGIDAndDateRange calls ReadByGIDAndDateRangeFunc.
func (mock *DetectedSpamMock) ReadByGIDAndDateRange(ctx context.Context, gid string, from time.Time, to time.Time) ([]storage.DetectedSpamInfo, error) {
	if mock.ReadByGIDAndDateRangeFunc == nil {
		panic("DetectedSpamMock.ReadByGIDAndDateRangeFunc: method is nil but DetectedSpam.ReadByGIDAndDateRange was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Gid  string
		From time.Time
		To   time.Time
	}{
		Ctx:  ctx,
		Gid:  gid,
		From: from,
		To:   to,
	}
	mock.lockReadByGIDAndDateRange.Lock()
	mock.calls.ReadByGIDAndDateRange = append(mock.calls.ReadByGIDAndDateRange, callInfo)
	mock.lockReadByGIDAndDateRange.Unlock()
	return mock.ReadByGIDAndDateRangeFunc(ctx, gid, from, to)
}

// ReadByGIDAndDateRangeCalls gets all the calls that were made to ReadByGIDAndDateRange.
// Check the length with:
//
//	len(mockedDetectedSpam.ReadByGIDAndDateRangeCalls())
func (mock *DetectedSpamMock) ReadByGIDAndDateRangeCalls() []struct {
	Ctx  context.Context
	Gid  string
	From time.Time
	To   time.Time
} {
	var calls []struct {
		Ctx  context.Context
		Gid  string
		From time.Time
		To   time.Time
	}
	mock.lockReadByGIDAndDateRange.RLock()
	calls = mock.calls.ReadByGIDAndDateRange
	mock.lockReadByGIDAndDateRange.RUnlock()
	return calls
}

// ResetReadByGIDAndDateRangeCalls reset all the calls that were made to ReadByGIDAndDateRange.
func (mock *DetectedSpamMock) ResetReadByGIDAndDateRangeCalls() {
	mock.lockReadByGIDAndDateRange.Lock()
	mock.calls.ReadByGIDAndDateRange = nil
	mock.lockReadByGIDAndDateRange.Unlock()
}

// SetAddedToSamplesFlag calls SetAddedToSamplesFlagFunc.
func (mock *DetectedSpamMock) SetAddedToSamplesFlag(ctx context.Context, id int64) error {
	if mock.SetAddedToSamplesFlagFunc == nil {
		panic("DetectedSpamMock.SetAddedToSamplesFlagFunc: method is nil but DetectedSpam.SetAddedToSamplesFlag was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = append(mock.calls.SetAddedToSamplesFlag, callInfo)
	mock.lockSetAddedToSamplesFlag.Unlock()
	return mock.SetAddedToSamplesFlagFunc(ctx, id)
}

// SetAddedToSamplesFlagCalls gets all the calls that were made to SetAddedToSamplesFlag.
// Check the length with:
//
//	len(mockedDetectedSpam.SetAddedToSamplesFlagCalls())
func (mock *DetectedSpamMock) SetAddedToSamplesFlagCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockSetAddedToSamplesFlag.RLock()
	calls = mock.calls.SetAddedToSamplesFlag
	mock.lockSetAddedToSamplesFlag.RUnlock()
	return calls
}

// ResetSetAddedToSamplesFlagCalls reset all the calls that were made to SetAddedToSamplesFlag.
func (mock *DetectedSpamMock) ResetSetAddedToSamplesFlagCalls() {
	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = nil
	mock.lockSetAddedToSamplesFlag.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *DetectedSpamMock) ResetCalls() {
	mock.lockFindByUserID.Lock()
	mock.calls.FindByUserID = nil
	mock.lockFindByUserID.Unlock()

	mock.lockRead.Lock()
	mock.calls.Read = nil
	mock.lockRead.Unlock()

	mock.lockReadByGID.Lock()
	mock.calls.ReadByGID = nil
	mock.lockReadByGID.Unlock()

	mock.lockReadByGIDAndDateRange.Lock()
	mock.calls.ReadByGIDAndDateRange = nil
	mock.lockReadByGIDAndDateRange.Unlock()

	mock.lockSetAddedToSamplesFlag.Lock()
	mock.calls.SetAddedToSamplesFlag = nil
	mock.lockSetAddedToSamplesFlag.Unlock()
}
